# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


"""
This is the python wrapper for E7XX Piezo Stage library.
"""


from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_E7XX_swig', [dirname(__file__)])
        except ImportError:
            import _E7XX_swig
            return _E7XX_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_E7XX_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _E7XX_swig = swig_import_helper()
    del swig_import_helper
else:
    import _E7XX_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_doubleArray(*args):
  return _E7XX_swig.new_doubleArray(*args)
new_doubleArray = _E7XX_swig.new_doubleArray

def delete_doubleArray(*args):
  return _E7XX_swig.delete_doubleArray(*args)
delete_doubleArray = _E7XX_swig.delete_doubleArray

def doubleArray_getitem(*args):
  return _E7XX_swig.doubleArray_getitem(*args)
doubleArray_getitem = _E7XX_swig.doubleArray_getitem

def doubleArray_setitem(*args):
  return _E7XX_swig.doubleArray_setitem(*args)
doubleArray_setitem = _E7XX_swig.doubleArray_setitem

def new_intArray(*args):
  return _E7XX_swig.new_intArray(*args)
new_intArray = _E7XX_swig.new_intArray

def delete_intArray(*args):
  return _E7XX_swig.delete_intArray(*args)
delete_intArray = _E7XX_swig.delete_intArray

def intArray_getitem(*args):
  return _E7XX_swig.intArray_getitem(*args)
intArray_getitem = _E7XX_swig.intArray_getitem

def intArray_setitem(*args):
  return _E7XX_swig.intArray_setitem(*args)
intArray_setitem = _E7XX_swig.intArray_setitem

def E7XX_InterfaceSetupDlg(*args):
  """E7XX_InterfaceSetupDlg(char szRegKeyName) -> int"""
  return _E7XX_swig.E7XX_InterfaceSetupDlg(*args)

def E7XX_ConnectRS232(*args):
  """E7XX_ConnectRS232(int iPortNumber, int iBaudRate) -> int"""
  return _E7XX_swig.E7XX_ConnectRS232(*args)

def E7XX_ConnectNIgpib(*args):
  """E7XX_ConnectNIgpib(int iBoardNumber, int iDeviceAddress) -> int"""
  return _E7XX_swig.E7XX_ConnectNIgpib(*args)

def E7XX_ConnectPciBoard(*args):
  """E7XX_ConnectPciBoard(int iBoardNumber) -> int"""
  return _E7XX_swig.E7XX_ConnectPciBoard(*args)

def E7XX_ConnectPciBoardAndReboot(*args):
  """E7XX_ConnectPciBoardAndReboot(int iBoardNumber) -> int"""
  return _E7XX_swig.E7XX_ConnectPciBoardAndReboot(*args)

def E7XX_ChangeNIgpibAddress(*args):
  """E7XX_ChangeNIgpibAddress(int ID, int iDeviceAddress) -> BOOL"""
  return _E7XX_swig.E7XX_ChangeNIgpibAddress(*args)

def E7XX_IsConnected(*args):
  """E7XX_IsConnected(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_IsConnected(*args)

def E7XX_CloseConnection(*args):
  """E7XX_CloseConnection(int ID)"""
  return _E7XX_swig.E7XX_CloseConnection(*args)

def E7XX_GetError(*args):
  """E7XX_GetError(int ID) -> int"""
  return _E7XX_swig.E7XX_GetError(*args)

def E7XX_SetErrorCheck(*args):
  """E7XX_SetErrorCheck(int ID, BOOL bErrorCheck) -> BOOL"""
  return _E7XX_swig.E7XX_SetErrorCheck(*args)

def E7XX_TranslateError(*args):
  """E7XX_TranslateError(int iErrorNumber, char szErrorMessage) -> BOOL"""
  return _E7XX_swig.E7XX_TranslateError(*args)

def E7XX_CountPciBoards():
  """E7XX_CountPciBoards() -> int"""
  return _E7XX_swig.E7XX_CountPciBoards()

def E7XX_qERR(*args):
  """E7XX_qERR(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_qERR(*args)

def E7XX_qIDN(*args):
  """E7XX_qIDN(int ID, char szBuffer) -> BOOL"""
  return _E7XX_swig.E7XX_qIDN(*args)

def E7XX_INI(*args):
  """E7XX_INI(int ID, char szAxes) -> BOOL"""
  return _E7XX_swig.E7XX_INI(*args)

def E7XX_qHLP(*args):
  """E7XX_qHLP(int ID, char szBuffer) -> BOOL"""
  return _E7XX_swig.E7XX_qHLP(*args)

def E7XX_qHPA(*args):
  """E7XX_qHPA(int ID, char szBuffer) -> BOOL"""
  return _E7XX_swig.E7XX_qHPA(*args)

def E7XX_CSV(*args):
  """E7XX_CSV(int ID, double pdCommandSyntaxVersion) -> BOOL"""
  return _E7XX_swig.E7XX_CSV(*args)

def E7XX_qCSV(*args):
  """E7XX_qCSV(int ID, double pdCommandSyntaxVersion) -> BOOL"""
  return _E7XX_swig.E7XX_qCSV(*args)

def E7XX_qOVF(*args):
  """E7XX_qOVF(int ID, char szAxes, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qOVF(*args)

def E7XX_RBT(*args):
  """E7XX_RBT(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_RBT(*args)

def E7XX_REP(*args):
  """E7XX_REP(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_REP(*args)

def E7XX_qSSN(*args):
  """E7XX_qSSN(int ID, char szSerialNumber) -> BOOL"""
  return _E7XX_swig.E7XX_qSSN(*args)

def E7XX_qVER(*args):
  """E7XX_qVER(int ID, char szVersion) -> BOOL"""
  return _E7XX_swig.E7XX_qVER(*args)

def E7XX_CCT(*args):
  """E7XX_CCT(int ID, int iCommandType) -> BOOL"""
  return _E7XX_swig.E7XX_CCT(*args)

def E7XX_MOV(*args):
  """E7XX_MOV(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_MOV(*args)

def E7XX_qMOV(*args):
  """E7XX_qMOV(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qMOV(*args)

def E7XX_MVR(*args):
  """E7XX_MVR(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_MVR(*args)

def E7XX_qPOS(*args):
  """E7XX_qPOS(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qPOS(*args)

def E7XX_IsMoving(*args):
  """E7XX_IsMoving(int ID, char szAxes, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_IsMoving(*args)

def E7XX_HLT(*args):
  """E7XX_HLT(int ID, char szAxes) -> BOOL"""
  return _E7XX_swig.E7XX_HLT(*args)

def E7XX_qONT(*args):
  """E7XX_qONT(int ID, char szAxes, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qONT(*args)

def E7XX_SVA(*args):
  """E7XX_SVA(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_SVA(*args)

def E7XX_qSVA(*args):
  """E7XX_qSVA(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qSVA(*args)

def E7XX_SVR(*args):
  """E7XX_SVR(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_SVR(*args)

def E7XX_DFH(*args):
  """E7XX_DFH(int ID, char szAxes) -> BOOL"""
  return _E7XX_swig.E7XX_DFH(*args)

def E7XX_qDFH(*args):
  """E7XX_qDFH(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qDFH(*args)

def E7XX_GOH(*args):
  """E7XX_GOH(int ID, char szAxes) -> BOOL"""
  return _E7XX_swig.E7XX_GOH(*args)

def E7XX_DFF(*args):
  """E7XX_DFF(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_DFF(*args)

def E7XX_qDFF(*args):
  """E7XX_qDFF(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qDFF(*args)

def E7XX_qCST(*args):
  """E7XX_qCST(int ID, char szAxes, char szNames) -> BOOL"""
  return _E7XX_swig.E7XX_qCST(*args)

def E7XX_CST(*args):
  """E7XX_CST(int ID, char szAxes, char szNames) -> BOOL"""
  return _E7XX_swig.E7XX_CST(*args)

def E7XX_qVST(*args):
  """E7XX_qVST(int ID, char szValideStages) -> BOOL"""
  return _E7XX_swig.E7XX_qVST(*args)

def E7XX_qTVI(*args):
  """E7XX_qTVI(int ID, char szPossibleAxisCharacters) -> BOOL"""
  return _E7XX_swig.E7XX_qTVI(*args)

def E7XX_SVO(*args):
  """E7XX_SVO(int ID, char szAxes, int pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_SVO(*args)

def E7XX_qSVO(*args):
  """E7XX_qSVO(int ID, char szAxes, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qSVO(*args)

def E7XX_VCO(*args):
  """E7XX_VCO(int ID, char szAxes, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_VCO(*args)

def E7XX_qVCO(*args):
  """E7XX_qVCO(int ID, char szAxes, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qVCO(*args)

def E7XX_VEL(*args):
  """E7XX_VEL(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_VEL(*args)

def E7XX_qVEL(*args):
  """E7XX_qVEL(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qVEL(*args)

def E7XX_SPA(*args):
  """
    E7XX_SPA(int ID, char szAxes, int iParameterArray, double pdValueArray, 
        char szStrings) -> BOOL
    """
  return _E7XX_swig.E7XX_SPA(*args)

def E7XX_qSPA(*args):
  """
    E7XX_qSPA(int ID, char szAxes, int iParameterArray, double pdValueArray, 
        char szStrings, int iMaxStringSize) -> BOOL
    """
  return _E7XX_swig.E7XX_qSPA(*args)

def E7XX_SEP(*args):
  """
    E7XX_SEP(int ID, char szPassword, char szAxes, int iParameterArray, 
        double pdValueArray, char szStrings) -> BOOL
    """
  return _E7XX_swig.E7XX_SEP(*args)

def E7XX_qSEP(*args):
  """
    E7XX_qSEP(int ID, char szAxes, int iParameterArray, double pdValueArray, 
        char szStrings, int iMaxStringSize) -> BOOL
    """
  return _E7XX_swig.E7XX_qSEP(*args)

def E7XX_WPA(*args):
  """E7XX_WPA(int ID, char szPassword, char szAxes, int iParameterArray) -> BOOL"""
  return _E7XX_swig.E7XX_WPA(*args)

def E7XX_RPA(*args):
  """E7XX_RPA(int ID, char szAxes, int iParameterArray) -> BOOL"""
  return _E7XX_swig.E7XX_RPA(*args)

def E7XX_SPA_String(*args):
  """E7XX_SPA_String(int ID, char szAxes, int iParameterArray, char szStrings) -> BOOL"""
  return _E7XX_swig.E7XX_SPA_String(*args)

def E7XX_qSPA_String(*args):
  """
    E7XX_qSPA_String(int ID, char szAxes, int iParameterArray, char szStrings, 
        int iMaxStringSize) -> BOOL
    """
  return _E7XX_swig.E7XX_qSPA_String(*args)

def E7XX_SEP_String(*args):
  """
    E7XX_SEP_String(int ID, char szPassword, char szAxes, int iParameterArray, 
        char szStrings) -> BOOL
    """
  return _E7XX_swig.E7XX_SEP_String(*args)

def E7XX_qSEP_String(*args):
  """
    E7XX_qSEP_String(int ID, char szAxes, int iParameterArray, char szStrings, 
        int iMaxStringSize) -> BOOL
    """
  return _E7XX_swig.E7XX_qSEP_String(*args)

def E7XX_STE(*args):
  """E7XX_STE(int ID, char cAxis, double dStepSize) -> BOOL"""
  return _E7XX_swig.E7XX_STE(*args)

def E7XX_qSTE(*args):
  """
    E7XX_qSTE(int ID, char cAxis, int iOffsetOfFirstPointInRecordTable, 
        int iNumberOfValues, double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_qSTE(*args)

def E7XX_IMP(*args):
  """E7XX_IMP(int ID, char cAxis, double dImpulseSize) -> BOOL"""
  return _E7XX_swig.E7XX_IMP(*args)

def E7XX_IMP_PulseWidth(*args):
  """E7XX_IMP_PulseWidth(int ID, char cAxis, double dImpulseSize, int iPulseWidth) -> BOOL"""
  return _E7XX_swig.E7XX_IMP_PulseWidth(*args)

def E7XX_qIMP(*args):
  """
    E7XX_qIMP(int ID, char cAxis, int iOffsetOfFirstPointInRecordTable, 
        int iNumberOfValues, double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_qIMP(*args)

def E7XX_SAI(*args):
  """E7XX_SAI(int ID, char szOldAxes, char szNewAxes) -> BOOL"""
  return _E7XX_swig.E7XX_SAI(*args)

def E7XX_qSAI(*args):
  """E7XX_qSAI(int ID, char axes) -> BOOL"""
  return _E7XX_swig.E7XX_qSAI(*args)

def E7XX_qSAI_ALL(*args):
  """E7XX_qSAI_ALL(int ID, char axes) -> BOOL"""
  return _E7XX_swig.E7XX_qSAI_ALL(*args)

def E7XX_CCL(*args):
  """E7XX_CCL(int ID, int iComandLevel, char szPassWord) -> BOOL"""
  return _E7XX_swig.E7XX_CCL(*args)

def E7XX_qCCL(*args):
  """E7XX_qCCL(int ID, int piComandLevel) -> BOOL"""
  return _E7XX_swig.E7XX_qCCL(*args)

def E7XX_AVG(*args):
  """E7XX_AVG(int ID, int iAverrageTime) -> BOOL"""
  return _E7XX_swig.E7XX_AVG(*args)

def E7XX_qAVG(*args):
  """E7XX_qAVG(int ID, int iAverrageTime) -> BOOL"""
  return _E7XX_swig.E7XX_qAVG(*args)

def E7XX_DIO(*args):
  """E7XX_DIO(int ID, char szChannels, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_DIO(*args)

def E7XX_qTIO(*args):
  """E7XX_qTIO(int ID, int piInputNr, int piOutputNr) -> BOOL"""
  return _E7XX_swig.E7XX_qTIO(*args)

def E7XX_E7XXSendString(*args):
  """E7XX_E7XXSendString(int ID, char szString) -> BOOL"""
  return _E7XX_swig.E7XX_E7XXSendString(*args)

def E7XX_E7XXGetLineSize(*args):
  """E7XX_E7XXGetLineSize(int ID, int iLineSize) -> BOOL"""
  return _E7XX_swig.E7XX_E7XXGetLineSize(*args)

def E7XX_E7XXReadLine(*args):
  """E7XX_E7XXReadLine(int ID, char szString, int iBufferSize) -> BOOL"""
  return _E7XX_swig.E7XX_E7XXReadLine(*args)

def E7XX_GcsCommandset(*args):
  """E7XX_GcsCommandset(int ID, char szCommand) -> BOOL"""
  return _E7XX_swig.E7XX_GcsCommandset(*args)

def E7XX_GcsGetAnswer(*args):
  """E7XX_GcsGetAnswer(int ID, char szAnswer, int iBufferSize) -> BOOL"""
  return _E7XX_swig.E7XX_GcsGetAnswer(*args)

def E7XX_GcsGetAnswerSize(*args):
  """E7XX_GcsGetAnswerSize(int ID, int iAnswerSize) -> BOOL"""
  return _E7XX_swig.E7XX_GcsGetAnswerSize(*args)

def E7XX_ATZ(*args):
  """E7XX_ATZ(int ID, char szAxes, double pdLowVoltageArray, BOOL pfUseDefaultArray) -> BOOL"""
  return _E7XX_swig.E7XX_ATZ(*args)

def E7XX_qTMN(*args):
  """E7XX_qTMN(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qTMN(*args)

def E7XX_qTMX(*args):
  """E7XX_qTMX(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qTMX(*args)

def E7XX_NLM(*args):
  """E7XX_NLM(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_NLM(*args)

def E7XX_qNLM(*args):
  """E7XX_qNLM(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qNLM(*args)

def E7XX_PLM(*args):
  """E7XX_PLM(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_PLM(*args)

def E7XX_qPLM(*args):
  """E7XX_qPLM(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qPLM(*args)

def E7XX_GetRefResult(*args):
  """E7XX_GetRefResult(int ID, char szAxes, int piReferenceResult) -> BOOL"""
  return _E7XX_swig.E7XX_GetRefResult(*args)

def E7XX_WAV_SIN_P(*args):
  """
    E7XX_WAV_SIN_P(int ID, char szWaveTableId, int iOffsetOfFirstPointInWaveTable, 
        int iNumberOfPoints, int iAddAppendWave, 
        int iCenterPointOfWave, double dAmplitudeOfWave, 
        double dOffsetOfWave, int iSegmentLength) -> BOOL
    """
  return _E7XX_swig.E7XX_WAV_SIN_P(*args)

def E7XX_WAV_LIN(*args):
  """
    E7XX_WAV_LIN(int ID, char szWaveTableId, int iOffsetOfFirstPointInWaveTable, 
        int iNumberOfPoints, int iAddAppendWave, 
        int iNumberOfSpeedUpDownPointsInWave, 
        double dAmplitudeOfWave, double dOffsetOfWave, 
        int iSegmentLength) -> BOOL
    """
  return _E7XX_swig.E7XX_WAV_LIN(*args)

def E7XX_WAV_RAMP(*args):
  """
    E7XX_WAV_RAMP(int ID, char szWaveTableId, int iOffsetOfFirstPointInWaveTable, 
        int iNumberOfPoints, int iAddAppendWave, 
        int iCenterPointOfWave, int iNumberOfSpeedUpDownPointsInWave, 
        double dAmplitudeOfWave, 
        double dOffsetOfWave, int iSegmentLength) -> BOOL
    """
  return _E7XX_swig.E7XX_WAV_RAMP(*args)

def E7XX_WAV_PNT(*args):
  """
    E7XX_WAV_PNT(int ID, char szWaveTableId, int iOffsetOfFirstPointInWaveTable, 
        int iNumberOfPoints, int iAddAppendWave, 
        double pdWavePoints) -> BOOL
    """
  return _E7XX_swig.E7XX_WAV_PNT(*args)

def E7XX_qWAV(*args):
  """
    E7XX_qWAV(int ID, char szWaveTableIds, int piParamereIdsArray, 
        double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_qWAV(*args)

def E7XX_qGWD(*args):
  """
    E7XX_qGWD(int ID, char cWaveTableId, int iOffsetOfFirstPointInWaveTable, 
        int iNumberOfValues, double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_qGWD(*args)

def E7XX_WGO(*args):
  """E7XX_WGO(int ID, char szWaveGeneratorIds, int iStartModArray) -> BOOL"""
  return _E7XX_swig.E7XX_WGO(*args)

def E7XX_qWGO(*args):
  """E7XX_qWGO(int ID, char szWaveGeneratorIds, int piValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qWGO(*args)

def E7XX_WGC(*args):
  """E7XX_WGC(int ID, char szWaveGeneratorIds, int piNumberOfCyclesArray) -> BOOL"""
  return _E7XX_swig.E7XX_WGC(*args)

def E7XX_qWGC(*args):
  """E7XX_qWGC(int ID, char szWaveGeneratorIds, int piValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qWGC(*args)

def E7XX_qTNR(*args):
  """E7XX_qTNR(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_qTNR(*args)

def E7XX_DRC(*args):
  """
    E7XX_DRC(int ID, int piRecordChannelIdsArray, char szRecordSourceIds, 
        int piRecordOptionArray, int piTriggerOption) -> BOOL
    """
  return _E7XX_swig.E7XX_DRC(*args)

def E7XX_qDRC(*args):
  """
    E7XX_qDRC(int ID, int piRecordChannelIdsArray, char szRecordSourceIds, 
        int piRecordOptionArray, int piTriggerOption, 
        int iArraySize) -> BOOL
    """
  return _E7XX_swig.E7XX_qDRC(*args)

def E7XX_WGR(*args):
  """E7XX_WGR(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_WGR(*args)

def E7XX_qDRR_SYNC(*args):
  """
    E7XX_qDRR_SYNC(int ID, int iRecordChannelId, int iOffsetOfFirstPointInRecordTable, 
        int iNumberOfValues, double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_qDRR_SYNC(*args)

def E7XX_RTR(*args):
  """E7XX_RTR(int ID, int iReportTableRate) -> BOOL"""
  return _E7XX_swig.E7XX_RTR(*args)

def E7XX_qRTR(*args):
  """E7XX_qRTR(int ID, int piReportTableRate) -> BOOL"""
  return _E7XX_swig.E7XX_qRTR(*args)

def E7XX_qTWG(*args):
  """E7XX_qTWG(int ID, int piGenerator) -> BOOL"""
  return _E7XX_swig.E7XX_qTWG(*args)

def E7XX_WMS(*args):
  """E7XX_WMS(int ID, char szWaveTablesIds, int iMaxWaveSize) -> BOOL"""
  return _E7XX_swig.E7XX_WMS(*args)

def E7XX_qWMS(*args):
  """E7XX_qWMS(int ID, char szWaveTablesIds, int iMaxWaveSize) -> BOOL"""
  return _E7XX_swig.E7XX_qWMS(*args)

def E7XX_DTC(*args):
  """E7XX_DTC(int ID, int iDdlTableId) -> BOOL"""
  return _E7XX_swig.E7XX_DTC(*args)

def E7XX_WCL(*args):
  """E7XX_WCL(int ID, int iWaveTableId) -> BOOL"""
  return _E7XX_swig.E7XX_WCL(*args)

def E7XX_DDL(*args):
  """
    E7XX_DDL(int ID, int iDdlTableId, int iOffsetOfFirstPointInDdlTable, 
        int iNumberOfValues, double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_DDL(*args)

def E7XX_qDDL(*args):
  """
    E7XX_qDDL(int ID, int iDdlTableId, int iOffsetOfFirstPointInDdlTable, 
        int iNumberOfValues, double pdValueArray) -> BOOL
    """
  return _E7XX_swig.E7XX_qDDL(*args)

def E7XX_TWS(*args):
  """
    E7XX_TWS(int ID, int piWavePointNumberArray, int piTriggerLevelArray, 
        int iNumberOfPoints) -> BOOL
    """
  return _E7XX_swig.E7XX_TWS(*args)

def E7XX_TWC(*args):
  """E7XX_TWC(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_TWC(*args)

def E7XX_qTLT(*args):
  """E7XX_qTLT(int ID, int piDdlTables) -> BOOL"""
  return _E7XX_swig.E7XX_qTLT(*args)

def E7XX_DPO(*args):
  """E7XX_DPO(int ID, char szAxes) -> BOOL"""
  return _E7XX_swig.E7XX_DPO(*args)

def E7XX_IsGeneratorRunning(*args):
  """E7XX_IsGeneratorRunning(int ID, char szWaveGeneratorIds, BOOL pbValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_IsGeneratorRunning(*args)

def E7XX_VMA(*args):
  """E7XX_VMA(int ID, char szPiezoChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_VMA(*args)

def E7XX_qVMA(*args):
  """E7XX_qVMA(int ID, char szPiezoChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qVMA(*args)

def E7XX_VMI(*args):
  """E7XX_VMI(int ID, char szPiezoChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_VMI(*args)

def E7XX_qVMI(*args):
  """E7XX_qVMI(int ID, char szPiezoChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qVMI(*args)

def E7XX_VOL(*args):
  """E7XX_VOL(int ID, char szPiezoChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_VOL(*args)

def E7XX_qVOL(*args):
  """E7XX_qVOL(int ID, char szPiezoChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qVOL(*args)

def E7XX_qTPC(*args):
  """E7XX_qTPC(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_qTPC(*args)

def E7XX_qTAD(*args):
  """E7XX_qTAD(int ID, char szSensorChannels, int piValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qTAD(*args)

def E7XX_qTNS(*args):
  """E7XX_qTNS(int ID, char szSensorChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qTNS(*args)

def E7XX_qTSP(*args):
  """E7XX_qTSP(int ID, char szSensorChannels, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_qTSP(*args)

def E7XX_qTSC(*args):
  """E7XX_qTSC(int ID) -> BOOL"""
  return _E7XX_swig.E7XX_qTSC(*args)

def E7XX_qTAV(*args):
  """E7XX_qTAV(int ID, char szAnalogInputChannels, int piValarray) -> BOOL"""
  return _E7XX_swig.E7XX_qTAV(*args)

def E7XX_GetSupportedFunctions(*args):
  """
    E7XX_GetSupportedFunctions(int ID, int piComandLevelArray, int iMaxlen, char szFunctionNames, 
        int iMaxFunctioNamesLength) -> BOOL
    """
  return _E7XX_swig.E7XX_GetSupportedFunctions(*args)

def E7XX_GetSupportedParameters(*args):
  """
    E7XX_GetSupportedParameters(int ID, int piParameterIdArray, int piComandLevelArray, 
        int piMennoryLocationArray, int iMaxlen, 
        char szParameterName, int iMaxParameterNameSize) -> BOOL
    """
  return _E7XX_swig.E7XX_GetSupportedParameters(*args)

def E7XX_GetSupportedControllers(*args):
  """E7XX_GetSupportedControllers(char szBuffer) -> BOOL"""
  return _E7XX_swig.E7XX_GetSupportedControllers(*args)

def E7XX_NMOV(*args):
  """E7XX_NMOV(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_NMOV(*args)

def E7XX_NMVR(*args):
  """E7XX_NMVR(int ID, char szAxes, double pdValueArray) -> BOOL"""
  return _E7XX_swig.E7XX_NMVR(*args)

def E7XX_TWS_EQU_DIST(*args):
  """
    E7XX_TWS_EQU_DIST(int ID, int iTriggerPointStart, int iTriggerDistance, 
        int iTriggerPointsPerPuls, int iTriggerPointsCount, 
        int iTriggerLevel) -> BOOL
    """
  return _E7XX_swig.E7XX_TWS_EQU_DIST(*args)

def E7XX_WAV_LIN_SPEED_UP(*args):
  """E7XX_WAV_LIN_SPEED_UP(int ID, int iSpeedUpDown, double rSpeed, double rSpeedUpDown) -> BOOL"""
  return _E7XX_swig.E7XX_WAV_LIN_SPEED_UP(*args)

def E761_SetDirectTarget(*args):
  """E761_SetDirectTarget(int ID, PI_E761_DIRECT_TARGET_WRITE piDirectTargetData) -> BOOL"""
  return _E7XX_swig.E761_SetDirectTarget(*args)

def E761_GetDirectPosition(*args):
  """E761_GetDirectPosition(int ID, PI_E761_DIRECT_POSITION_READ ppiDirectPositionData) -> BOOL"""
  return _E7XX_swig.E761_GetDirectPosition(*args)
# This file is compatible with both classic and new-style classes.


